# Generated by Django 2.2.20 on 2021-06-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='telegram_id',
        ),
    ]
