# Generated by Django 3.2.4 on 2021-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210614_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user_lst',
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='programming', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
