# Generated by Django 3.2.4 on 2021-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
