# Generated by Django 3.2.4 on 2021-06-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
